# Generated by Django 5.2.13 on 2026-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeChatApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='申請學生')),
                ('alumni_name', models.CharField(max_length=50, verbose_name='預約校友')),
                ('scheduled_time', models.CharField(max_length=100, verbose_name='預約時段')),
                ('experience_summary', models.TextField(verbose_name='自身經歷簡述')),
                ('question_outline', models.TextField(verbose_name='具體提問大綱')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='處理進度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
